/**
 * @claude-flow/copilot - Config generator
 *
 * Copilot's session config is naturally JSON (per the SDK), but for
 * symmetry with the codex adapter we also emit a TOML-flavored
 * `.copilot/config.toml` so projects can keep one config surface.
 *
 * Two emitters:
 *   - generateCopilotConfigJson — `.copilot/config.json` (canonical)
 *   - generateConfigToml         — `.copilot/config.toml`  (compat)
 */

import type { CopilotMcpServerConfig, SkillConfig } from '../types.js';

export interface CopilotConfigOptions {
  model?: string;
  tier2Model?: string;
  tier3FrontierModel?: string;
  permissionHandler?: 'approve-all' | 'deny-all' | 'custom';
  streaming?: boolean;
  mcpServers?: Record<string, CopilotMcpServerConfig>;
  skills?: SkillConfig[];
  /** Per-call timeout in ms */
  timeoutMs?: number;
}

const DEFAULT_OPTIONS: Required<Omit<CopilotConfigOptions, 'mcpServers' | 'skills'>> = {
  model: 'gpt-5.3-codex',
  tier2Model: 'gpt-5.4-mini',
  tier3FrontierModel: 'gpt-5.5',
  permissionHandler: 'approve-all',
  streaming: false,
  timeoutMs: 300_000,
};

/**
 * JSON config (canonical). This is the file `CopilotInitializer`
 * writes to `.copilot/config.json`.
 */
export async function generateCopilotConfigJson(
  options: CopilotConfigOptions = {},
): Promise<string> {
  const merged = { ...DEFAULT_OPTIONS, ...options };
  const body: Record<string, unknown> = {
    $schema: 'https://github.com/ruvnet/ruflo/schemas/copilot-config-v1.json',
    model: merged.model,
    tiers: {
      tier2: merged.tier2Model,
      tier3: merged.model,
      tier3Reasoning: merged.tier3FrontierModel,
    },
    permissionHandler: merged.permissionHandler,
    streaming: merged.streaming,
    timeoutMs: merged.timeoutMs,
    mcpServers: options.mcpServers ?? {
      ruflo: {
        type: 'local',
        command: 'npx',
        args: ['-y', 'ruflo@latest', 'mcp', 'start'],
        tools: ['*'],
      },
    },
    skills: options.skills ?? [],
  };
  return JSON.stringify(body, null, 2) + '\n';
}

/**
 * TOML config (compat). Mirrors the codex generator's shape.
 */
export async function generateConfigToml(
  options: CopilotConfigOptions = {},
): Promise<string> {
  const merged = { ...DEFAULT_OPTIONS, ...options };
  const lines: string[] = [];
  lines.push('# =============================================================================');
  lines.push('# Claude Flow V3 - Copilot Configuration');
  lines.push('# Generated by: @claude-flow/copilot');
  lines.push('# Documentation: https://github.com/ruvnet/ruflo');
  lines.push('# =============================================================================');
  lines.push('');
  lines.push('# Model defaults');
  lines.push(`model = "${merged.model}"`);
  lines.push(`tier2_model = "${merged.tier2Model}"`);
  lines.push(`tier3_frontier_model = "${merged.tier3FrontierModel}"`);
  lines.push('');
  lines.push('# Session behavior');
  lines.push(`permission_handler = "${merged.permissionHandler}"`);
  lines.push(`streaming = ${merged.streaming}`);
  lines.push(`timeout_ms = ${merged.timeoutMs}`);
  lines.push('');

  // MCP servers
  lines.push('# =============================================================================');
  lines.push('# MCP Servers');
  lines.push('# =============================================================================');
  lines.push('');
  const servers = options.mcpServers ?? {
    ruflo: {
      type: 'local' as const,
      command: 'npx',
      args: ['-y', 'ruflo@latest', 'mcp', 'start'],
      tools: ['*'],
    },
  };
  for (const [name, server] of Object.entries(servers)) {
    lines.push(`[mcp_servers.${name}]`);
    lines.push(`type = "${server.type}"`);
    if (server.command) lines.push(`command = "${server.command}"`);
    if (server.args) lines.push(`args = [${server.args.map((a) => `"${a}"`).join(', ')}]`);
    if (server.url) lines.push(`url = "${server.url}"`);
    if (server.tools) {
      const toolsArr = Array.isArray(server.tools) ? server.tools : [server.tools];
      lines.push(`tools = [${toolsArr.map((t) => `"${t}"`).join(', ')}]`);
    }
    if (server.timeout !== undefined) lines.push(`timeout = ${server.timeout}`);
    lines.push('');
  }

  // Skills
  const skills = options.skills ?? [];
  if (skills.length > 0) {
    lines.push('# =============================================================================');
    lines.push('# Skills');
    lines.push('# =============================================================================');
    lines.push('');
    for (const skill of skills) {
      lines.push('[[skills.config]]');
      lines.push(`path = "${skill.path}"`);
      lines.push(`enabled = ${skill.enabled ?? true}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Minimal config helper.
 */
export async function generateMinimalConfig(options: CopilotConfigOptions = {}): Promise<string> {
  const merged = { ...DEFAULT_OPTIONS, ...options };
  return [
    '# Claude Flow V3 - Minimal Copilot Configuration',
    '',
    `model = "${merged.model}"`,
    `permission_handler = "${merged.permissionHandler}"`,
    '',
    '[mcp_servers.ruflo]',
    'type = "local"',
    'command = "npx"',
    'args = ["-y", "ruflo@latest", "mcp", "start"]',
    'tools = ["*"]',
    '',
  ].join('\n');
}

/**
 * CI-flavored config helper.
 */
export async function generateCIConfig(): Promise<string> {
  return [
    '# Claude Flow V3 - Copilot CI Configuration',
    '',
    'model = "gpt-5.4-mini"',
    'permission_handler = "deny-all"',
    'streaming = false',
    'timeout_ms = 120000',
    '',
    '[mcp_servers.ruflo]',
    'type = "local"',
    'command = "npx"',
    'args = ["-y", "ruflo@latest", "mcp", "start"]',
    'tools = ["memory_search", "memory_store"]',
    '',
  ].join('\n');
}
